- s3/s3.go
when using `Range: bytes=xxxx-xxxx` header to [S3 GET Object](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html), S3 returns response with `206 Partial Content`.
so S3.run() should allow status code 206.
> HTTP response 206(Partial Content)

- sqs/responses_test.go
- sqs/sqs.go
- sqs/sqs_test.go
Added Queue.SendMessageWithAttributes to SQS, attributes can only be string for now.
I tested it against the real API and it works.
Let me know if I need to change something in order to get this feature merged.
Thanks!
> Added Queue.SendMessageWithAttributes to SQS

- aws/aws.go
- aws/aws_test.go
Originally added to mitchellh/goamz by https://github.com/mitchellh/goamz/commit/19bd918f6ca130fe1fa7e9860df35b8b84f8a2d4 (and since updated slightly).
Wording from that commit: "Most AWS SDKs now support the use of shared profiles in
~/.aws/credentials. The AWS_PROFILE environment variable is then used to
pick the profile to be used."
Adds a dependency on vaughan0/go-ini 
This is just a copy/paste by me (o172) as I need this feature, and I'm using goamz/goamz for cloudformation support.
> Added SharedAuth method, from mitchellh/goamz

- ec2/ec2.go
- ec2/ec2_test.go
- ec2/responses_test.go
AuthorizeSecurityGroup and RevokeSecurityGroup should probably be renamed to include Ingress to match the API but are left for backwards compatibility.
I could add the correctly named functions and just call them from the existing functions. Thoughts?
> adding support for egress rules

- elb/elb.go
- elb/elb_test.go
- elb/response_test.go
- Keep the tags sorted so the maintain a consistent order when sent to
AWS
- Again, no integration tests here
> Adds ability to tag ELB resources

- elb/elb.go
- elb/elb_test.go
- elb/response_test.go
Also switched around my failure test response to be shared between both tests (it's exactly the same since it uses a common AWS failure).
> Adds ability to remove elb tags

- s3/s3.go
This is useful for Google AppEngine which requires the non-default urlfetch http client:
```go
context := appengine.NewContext(r)
httpclient := urlfetch.Client(context)
s3.New(auth, region, httpclient)
```
Feedback appreciated!  And thanks to everyone who has contributed to this great library.
> Adds s3 support for optional http clients

- dynamodb/query_builder.go
- dynamodb/table.go
At the moment this change allows you to modify the throughput on a DynamoDB table. More work is required to support adding/deleting/updating global-secondary-indexes.
> Adding support to update throughput on a DynamoDB table

- dynamodb/query.go
- dynamodb/query_builder.go
From what I could tell, there's no way to query an index in descending order (using the `scanIndexForward`) parameter. I could be wrong about this however - if there is a way, please let me know. 
In this PR I've added the functionality to query_builder.go and query.go - It results in a lot of additional functions. In general I don't like this approach, as it leads to a lot of duplicate code as a way of exposing non-attributeComparison parameters. If further parameters are to be added, I'd recommended exposing the buildQuery function to allow users to build their own queries and run them themselves.
> Allow for queries to scan index in descending order 

- s3/s3test/server.go
The AWS CLI expects the ETag header to be set to the MD5 of the uploaded file. The code currently does not do that for object PUT requests, as a result of which the AWS CLI fails when uploading to the test server.
This fix adds the ETag header (within double quotes) to the PUT response from the test server.  The double-quotes are necessary as the AWS CLI strips them out before performing an MD5 comparison of the uploaded file.
> Fix bug in s3Test Server

- s3/s3.go
Summary:
In some environments, the TLS handshake can fail, but the Go AWS client
doesn't retry. This change fixes the issue by levarging the net.Error()
interface since tlsHandshakeTimeoutError is not exposed. It fixes any
potential errors that are temporary in nature too.
> S3 doesn't retry upon getting tls-handshake timeout

- s3/s3.go
When running with a very high request rate, I've had problems with a rare few S3 requests failing with the RequestTimeout error code. No idea if this is on my end or S3's -- probably a connection not getting properly closed somewhere -- but it's definitely a temporary network error that would be appropriate to auto-retry.
> S3 retries on RequestTimeout

- s3/multi.go
- s3/multi_test.go
The multipart upload operation of s3 works by a sequence of calls.
The last one is multipart.Complete. The s3 semantics are rather
kludgy: if they can successfully start the process of completing a
multipart upload, they return HTTP 200, and periodically write a space
into the response body to maintain the connection. If the complete operation
fails during processing, that's passed to the client by putting an
Error element into the response body.
The go implementation of the multipart.Complete method wasn't checking
the message body, and was just declaring success when it saw the 200.
> Fix complete upload bug in s3 multipart upload.

- ecs/ecs.go
Per http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html, adds container env var overrides to goamz/ecs
> Adds ability to specify override environment variables in container overrides

- s3/s3t_test.go
- s3/s3test/server.go
I don't know if this is of any use to anyone. I quite like this s3test server so I am running one in a docker container and wanted to set the Host myself. Thought this might be of use to others so I thought I would open a PR :)
e.g.
```go
server, err := s3test.New(&s3test.Config{Host: "localhost:54322"})
...
```
> Add Host field to s3test.Config type for configuring s3test server host

- ec2/ec2.go
Based on documentation here [http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ImportKeyPair.html](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ImportKeyPair.html)
> Add ImportKeyPair to ec2

- s3/s3.go
PutCopy often fails with transient errors. This uses the attempt strategy to retry just like List, Head, DelBucket, etc.
> Use attempt strategy for PutCopy

- s3/s3.go
An application I'm developing was suffering from very high latency when connecting to S3, because we aren't reusing connections. This PR should fix it.
> Avoid closing connections to S3

- exp/ses/ses.go
- exp/ses/ses_types.go
the code was working fine in my dev, but was failing when running on EC2 that had an instance profile with sufficient privileges. I found the token header in another part of the code, so copying it over made things start working on EC2.
also corrected error response parsing so that an empty string is not returned as the error
> SES API returns 403 when using assumed role credentials from instance profile

- sqs/sqs.go
There is still a go vet warning for the tests but I left this out because test code doesn't end up in `/vendor`.
> fix go vet warnings

- aws/aws.go
- aws/regions.go
- sqs/sqs.go
Since (perhaps) goamz uses v4 signature in SQS at d9dce97b0a7877b5d866db68d165b0de57534109
I cannot use SQS using a url starting with "https://" (e.g. https://sqs.ap-northeast-2.amazonaws.com/).
goamz does not have a definition of ap-northeast-2 (Seoul) Region, I cannot use  ap-northeast-2 SQS.
> Add ap-northeast-2 Region

- s3/s3test/server.go
See https://github.com/aws/aws-sdk-go/blob/af3026711cd873ccb4e87a7142fa8ca0be8f2aef/private/protocol/rest/build.go#L22
```go
// RFC822 returns an RFC822 formatted timestamp for AWS protocols
const RFC822 = "Mon, 2 Jan 2006 15:04:05 GMT"
```
> Fix s3test Last-Modified time format

- s3/s3.go
There's a slight change in the behaviour of the Content-Length header
in tip, notably that sending a non-nil body and Content-Length of 0
results in the client not sending the Content-Length header.
See the following for justification and implmentation:
https://github.com/golang/go/commit/4859f6a416b053d57fcc9d8f43e81e9d218280e9
https://github.com/golang/go/blob/master/src/net/http/request.go#L1281-L1291
> Send nil Body when payload is empty

- exp/ses/ses.go
The https://golang.org/pkg/net/http/ states :
The client must close the response body when finished with it. 
The problem appears when we receive 200 from SES (success email sending). 
In this case the response body is not closed as it is not used but in order to prevent a memory leak the response body must be closed even when it is not used.
I observed it accidentally as when you'll send an email from a new go routine you'll encounter into permanently increasing number of go routines.
> The response body must be closed even when it is not used

- aws/client.go
- aws/sign.go
- cloudwatch/cloudwatch.go
- ec2/ec2.go
- s3/s3i_test.go
Hello all,
this PR adds `aws.NewResilientTransport` with an optional `http.Transport` argument, which provides more flexibility when creating an aws client. It fixes a `TODO` added in [f39dec7f](https://github.com/goamz/goamz/commit/f39dec7f0947912d3d89fed1caf8f60ea01d2698#diff-03cbd579aea1ff4a83f9f18400518b7bR48).
> Expose NewResilientTransport with optional http.Transport argument
